export default {
    GET_HOME_DATA: 'home/get_home_data',
    INIT_HOME_PAGE: 'home/init_home_page',
    GET_PRO_LIST: 'list/get_project_list',
    INIT_PRO_LIST: 'list/init_project_list',
    GET_DETAIL: 'detail/get_detail_data',
    INIT_PRO_DETAIL: 'detail/init_project_detail',
    GET_ACTIVS_DATA: 'activity/get_activity_list_data',
    INIT_ACTIVS_PAGE: 'activity/init_activity_list_page',
    GET_ACTIVITY_DETAIL: 'activity/get_activity_details',
    INIT_ACTIVITY_DETAIL: 'activity/init_activity_details',
    GET_PERSONAL_INFO: 'personal/get_personal_info',
	INIT_PERSONAL_PAGE: 'personal/init_personal_page',
	SUBMIT_APPLY: 'personal/submit_apply',
}
